systems/BD 114672.xml
systems/HD 103720.xml
systems/HD 108341.xml
systems/HD 113538.xml
systems/HD 30669.xml
systems/HD 564.xml

closes #429
created new systems HD 103720, HD 108341, HD 30669, HD 564, and updated data for BD 114672.
source: http://arxiv.org/abs/1412.6591

combined copy of all 6 systems.

---

systems/Kepler-93.xml

Closes #437 
(note the Travis build will likely fail due to an unrelated error in the Kepler-441 file)

Updated Kepler-93.

---

systems/HIP 67851.xml
systems/HIP 97233.xml

Added HIP 67851 and HIP 97233

---

systems/HD 131664.xml

Added HD 131664 b.

---

cleanup.py
oec.xsd

Added periastrontime tag.

---

systems/KIC 10001893.xml

Closes #334. Since the planet candidates are unnamed, I used the suffixes _1, _2 and _3 to match the article text.

Added KIC 10001893

---

systems/KOI-135.xml
systems/KOI-423.xml
systems/Kepler-41.xml
systems/Kepler-44.xml
systems/Kepler-74.xml
systems/Kepler-75.xml

Update Kepler-39, 41, 43, 44, 74, 75

---

systems/KOI-1894.xml
systems/Kepler-91.xml

Update Kepler-91, add KOI-1894

---

systems/Kepler-101.xml

Update values for Kepler-101

---

systems/Kepler-78.xml

Added missing values for Kepler-78

---

README.md

Missed this in earlier pull request.

Add periastrontime tag to README

---

systems/KOI-4427.xml
systems/Kepler-436.xml
systems/Kepler-437.xml
systems/Kepler-438.xml
systems/Kepler-439.xml
systems/Kepler-440.xml
systems/Kepler-441.xml
systems/Kepler-442.xml
systems/Kepler-443.xml

Update Kepler-436 to 443, added KOI-4427

---

systems/BD+49 828.xml
systems/HD 216536.xml
systems/HD 95127.xml

Niedzielski et al. (arXiv 2015) http://arxiv.org/abs/1501.07076

Added 3 red giant systems

---

systems/Kepler-445.xml
systems/Kepler-446.xml

http://arxiv.org/abs/1501.01305
Closes #447

added Kepler 445,446

---

systems/KOI-1299.xml

Updated KOI-1299

---

systems/HD 33142.xml

corrected coordinates (source SIMBAD)
own observation: http://www.lx200.de/img/ep-hd33142-20150206.jpg

Update HD 33142.xml

---

systems/2M 0746+20.xml
systems/2M 2206-20.xml
systems/BD+15 2940.xml
systems/HATS-4.xml
systems/HATS-5.xml
systems/HD 106906.xml
systems/HD 114613.xml
systems/HD 126614.xml
systems/HD 13908.xml
systems/HD 159243.xml
systems/HIP 91258.xml
systems/HW Vir.xml
systems/Kapteyn.xml
systems/Kepler-136.xml
systems/Kepler-197.xml
systems/Kepler-93.xml
systems/eta Cet.xml

Added magV, improved ra, de

---

systems/BD+20 1790.xml

source: http://arxiv.org/abs/1502.05223
Closes #486

Update and rename systems to systems/BD+20 1790.xml

---

systems/KOI-1612.xml
systems/Kepler-109.xml
systems/Kepler-117.xml
systems/Kepler-128.xml
systems/Kepler-13.xml
systems/Kepler-444.xml
systems/Kepler-78.xml
systems/Kepler-79.xml
systems_kepler/KOI-1612.xml

improved RA, DE, added magX, added alt. names; Source: SIMBAD
KOI-1612: Source: http://fr.arxiv.org/abs/1401.4195

improved RA, DE, added magX, added alt. names; Source: SIMBAD

---

systems/KELT-3.xml

corrected BD reference
corrected RA, DE
added star names
Source: SIMBAD
i found this error through own observations

KELT-3 has wrong position

---

systems/HATS-10.xml
systems/HATS-9.xml

Added HATS-9 and HATS-10

---

systems/EPIC 201367065.xml

Added K2 designation to EPIC 201367065

---

systems/HAT-P-14.xml
systems/HAT-P-16.xml
systems/HAT-P-24.xml
systems/HAT-P-30.xml
systems/HAT-P-32.xml
systems/HAT-P-33.xml
systems/HAT-P-7.xml
systems/HAT-P-8.xml
systems/TrES-2.xml
systems/TrES-4.xml
systems/WASP-1.xml
systems/WASP-11.xml
systems/WASP-12.xml
systems/WASP-14.xml
systems/WASP-2.xml
systems/WASP-3.xml
systems/WASP-8.xml

Stellar companions to hot Jupiter host stars

---

systems/HD 8673.xml

Added star HD 8673 B

---

systems/Kepler-13.xml

Added Kepler-13B,C; updated kepler-13Ab

---

systems/HATS-13.xml
systems/HATS-14.xml

added HATS-13, HATS-14

---

systems/HD 38858.xml

[Kennedy et al. (arXiv 2015)](http://arxiv.org/abs/1503.02073) section 5
For now I am holding off on adding the 198-day planet until its full parameters are published.

Move HD 38858 b to retracted planets list.

---

systems/HAT-P-50.xml
systems/HAT-P-51.xml
systems/HAT-P-52.xml
systems/HAT-P-53.xml

Source: http://arxiv.org/abs/1503.04149
closes #506

Added HAT-P 50,51,52,53

---

systems/HIP 67851.xml

Fix HIP designation on star HIP 67851.

---

systems/Kepler-19.xml

Ballard et al. (2011) http://iopscience.iop.org/0004-637X/743/2/200/

Add/update Kepler-19

---

systems/KOI-341.xml

Added Kepler-414.

---

systems/KOI-1194.xml

Added Kepler-415.

---

systems/HD 1605.xml
systems/HD 1666.xml
systems/HD 67087.xml

Source
http://arxiv.org/pdf/1503.07636v1.pdf
Positions and fluxes from SIMBAD
closes #532

added HD 1605, 1666, 67087, now with periastrontime

---

systems/EPIC 201208431.xml
systems/EPIC 201338508.xml
systems/EPIC 201384232.xml
systems/EPIC 201393098.xml
systems/EPIC 201577035.xml
systems/EPIC 201613023.xml
systems/EPIC 201629650.xml
systems/EPIC 201702477.xml
systems/EPIC 201736247.xml
systems/EPIC 201754305.xml
systems/EPIC 201855371.xml
systems/EPIC 201912552.xml

Source
http://arxiv.org/pdf/1503.07866v1
these systems will be added in another pull request since they are still in OEC and have to check: 201367065, 201505350

Add K2 Campaign 1 Planets - Part I

---

systems/EPIC 201295312.xml
systems/EPIC 201403446.xml
systems/EPIC 201445392.xml
systems/EPIC 201465501.xml
systems/EPIC 201546283.xml
systems/EPIC 201549860.xml
systems/EPIC 201565013.xml
systems/EPIC 201596316.xml
systems/EPIC 201617985.xml
systems/EPIC 201635569.xml
systems/EPIC 201828749.xml

Source
http://arxiv.org/pdf/1503.07866v1
Added 12 candidates in 11 systems

Add K2 Campaign 1 Planets - Part II - Candidates

---

systems/EPIC 201367065.xml

concerns still issue #534;
Source
http://arxiv.org/abs/1503.07866
Updated EPIC 201505350
planet d now marked as Controversial, since his discoverey is only announced in the first discovery paper
http://arxiv.org/abs/1503.00692
this part IV (EPIC 201367065) is the last part of issue #534

Add K2 Campaign 1 Planets - Part IV - Updated EPIC 201367065 #539

---

systems/EPIC 201367065.xml

planet d changed back to Confirmed as proposed by ajtribick

Update EPIC 201367065.xml

---

systems/KIC 10001893.xml
systems/KOI-183.xml
systems/KOI-188.xml
systems/KOI-192.xml
systems/KOI-195.xml
systems/KOI-314.xml
systems/KOI-830.xml
systems/Kepler-422.xml
systems/Kepler-423.xml
systems/Kepler-424.xml

Last part split out from the bulk Kepler update.
Addition of various missing designations, for details see individual commits.

Kepler update: last part

---

systems/KOI-1257.xml

Separate binary and primary star designations
Add Kepler-420 designations
Spacing of KIC identifier

Update KOI-1257 identifiers

---

systems/KIC 9632895.xml
systems/Kepler-34.xml
systems/Kepler-35.xml
systems/Kepler-38.xml
systems/Kepler-413.xml
systems/Kepler-47.xml

For details, see individual commits.

Identifier updates to Kepler circumbinary planet systems

---

systems/Kepler-56.xml

Fixed incorrect KIC identifier
Fixed incorrect declination
Added error bars to mass and radius values
Added inclinations to planets b and c
Added relative node value to planet c
Fixed incorrect discovery method for planet d
Demoted planet d to Controversial list: planetary nature not yet confirmed
Updated descriptions
Huber et al. (2013) http://adsabs.harvard.edu/abs/2013Sci...342..331H

Updated Kepler-56

---

systems/KOI-1474.xml

Dawson et al. (2012) http://adsabs.harvard.edu/abs/2012ApJ...761..163D
Dawson et al. (2014) http://adsabs.harvard.edu/abs/2014ApJ...791...89D
Additional information from NASA Confirmed Planet Overview

Added KOI-1474.

---

systems/Kepler-431.xml

Everett et al. (2015) http://adsabs.harvard.edu/abs/2015AJ....149...55E
Additional data from NASA Confirmed Planet Overview

Added Kepler-431.

---

systems/Kepler-37.xml

Add KOI-nnn.nn designations to Kepler-37 b,c,d
Add planet Kepler-37 e

Update system Kepler-37

---

systems/Kepler-430.xml

Everett et al. (2015) http://adsabs.harvard.edu/abs/2015AJ....149...55E
Additional data from NASA Confirmed Planet Overview

Added Kepler-430.

---

systems/KOI-2113.xml

Added Kepler-417.

---

systems/KOI-1860.xml

Added Kepler-416.

---

systems/MOA-2011-BLG-262L.xml

Add MOA-2011-BLG-262L

---

systems/2MASS 0122-2439.xml

Add 2MASS 0122-2439

---

systems/Rho Coronae Borealis.xml

Add Rho Coronae Borealis.

---

systems/GJ 160.2.xml
systems/GJ 180.xml
systems/GJ 229.xml
systems/GJ 27.1.xml
systems/GJ 422.xml
systems/GJ 682.xml

Closes #228 (Gliese 433 was already in the catalogue)

Added six systems

---

systems/WASP-80.xml

Updated WASP-80b temperature.

---

systems/Gliese 649.xml
systems/HD 117618.xml
systems/HD 3651.xml

Gliese 649 - closes #232
HD 3651, HD 117618 - closes #234

Added secondary planets from ambiguous RV solutions.

---

systems/HD 7924.xml

Source: http://arxiv.org/abs/1504.06629, Simbad
Closes #569

Added two super-Earths

---

systems/EPIC 201637175.xml
systems/KOI-12.xml
systems/KOI-372.xml

* KOI-12 - closes #556 
* KOI-372 - closes #560 
* EPIC 201637175 - closes #561

Add 3 systems

---

systems/CoRoT-28.xml
systems/CoRoT-29.xml

Source
http://arxiv.org/abs/1504.01532

Add CoRoT planets #543

---

systems/70 Vir.xml

Source http://arxiv.org/abs/1504.04066
closes #555

Update 70 Vir.xml

---

systems/XO-2.xml

Planetary/stellar properties:
Damasso et al. (2015) http://adsabs.harvard.edu/abs/2015A%26A...575A.111D
Closes #449 
Added note on stellar variability to XO-2Nb:
Zellem et al. (2015) http://arxiv.org/abs/1505.01063
Closes #578

Updated XO-2.

---

systems/Kepler-296.xml

Data from [Barclay et al. (2015)](http://arxiv.org/abs/1505.01845)
Closes #583

Updated Kepler-296

---

systems/KOI-368.xml

Updated description to reflect …more recent alignment value.
Ahlers et al. (2014) http://cdsads.u-strasbg.fr/abs/2014ApJ...786..131A

KOI-368.01 is likely an M-dwarf star.

---

systems/51 Peg.xml

Martins et al. (2015) http://cdsads.u-strasbg.fr/abs/2015A%26A...576A.134M
Closes #564

Update 51 Peg

---

systems/Kapteyn.xml

Robertson et al. (2015) http://arxiv.org/abs/1505.02778
Closes #585

Moved Kapteyn b to "controversial" list.

---

systems/55 Cancri.xml

Demory et al. (2015) http://arxiv.org/abs/1505.00269
Closes #577

Update 55 Cnc e

---

systems/CT Cha.xml

Wu et al. (2015) http://adsabs.harvard.edu/abs/2015ApJ...801....4W
Closes #450

Update CT Cha

---

systems/Gliese 876.xml

Updated stellar properties:
von Braun et al. (2014) http://adsabs.harvard.edu/abs/2014MNRAS.438.2413V
Update system properties:
Nelson et al. (2015) http://arxiv.org/abs/1504.07995
Closes #572

Update Gliese 876

---

systems/HAT-P-56.xml
systems/WASP-121.xml
systems/alf Tau.xml

Added WASP-121
Sources: http://arxiv.org/abs/1506.02471, SIMBAD
Closes #601
Added HAT-P-56
Sources: http://arxiv.org/abs/1506.01776, SIMBAD
Closes #600
Added alf Tau b as Controversial
Sources: http://arxiv.org/abs/1505.03454
Closes #587

Added WASP-121 b, HAT-P-56 b and as Controversial alf Tau b

---

systems/alf Tau.xml

Companion star to Aldebaran. Data from SIMBAD and WDS.

Added Aldebaran B

---

systems/OGLE-2013-BLG-0102L.xml

Jung et al. (2015) http://adsabs.harvard.edu/abs/2015ApJ...798..123J
Closes #296

Add OGLE-2013-BLG-0102L

---

systems/1RXS1609.xml
systems/GSC 06214-00210.xml
systems/HIP 78530.xml

Lechapelle et al. (2015) http://adsabs.harvard.edu/abs/2015ApJ...802...61L
Closes #535

Update Upper Scorpius planets

---

systems/2M 1938+4603.xml

Baran et al. (2015) http://dx.doi.org/10.1051/0004-6361/201425392
Additional parameters from
Østensen et al. (2010a) http://cdsads.u-strasbg.fr/abs/2010MNRAS.408L..51O
Østensen et al. (2010b) http://cdsads.u-strasbg.fr/abs/2010MNRAS.409.1470O
Closes #603

Added 2M 1938+4603

---

systems/Gliese 777.xml
systems/HD 164595.xml

http://arxiv.org/pdf/1506.07144.pdf
Closes #620

add warm jupiter, update gliese 777 planets

---

systems/BD+15 2940.xml

Update BD+15 2940.xml

---

systems/HAT-P-15.xml
systems/HAT-P-34.xml
systems/HAT-P-36.xml
systems/HATS-1.xml
systems/HD 233604.xml
systems/Kepler-18.xml
systems/WASP-121.xml

corrections in transittime and some coordinate improvements

corrections in transittime

---

systems/HATS-7.xml

Bakos et al. (2015) http://arxiv.org/abs/1507.01024

Added HATS-7b

---

systems/Kepler-100.xml
systems/Kepler-103.xml
systems/Kepler-107.xml
systems/Kepler-108.xml
systems/Kepler-109.xml

More updates for #586 
* Kepler-100 b,c,d
* Kepler-103 b,c
* Kepler-107 b,c,d,e
* Kepler-108 b,c
* Kepler-109 b,c

Photometric Kepler eccentricities part 2

---

systems/Kepler-42.xml

corrected transittime KOI-961.01

corrected Kepler-42 b transittime

---

systems/KMT-2015-1.xml
systems/OGLE-2012-BLG-0563L.xml
systems/OGLE-2013-BLG-0723L.xml

OGLE-2012-BLG-0563Lb - closes #622 
OGLE-2013-BLG-0723LBb - closes #631 
KMT-2015-1b - closes #638

Three microlensing planets

---

systems/KOI-370.xml
systems/Kepler-126.xml
systems/Kepler-127.xml
systems/Kepler-129.xml
systems/Kepler-130.xml
systems/Kepler-197.xml

More updates for #586
(Hopefully only one more batch of these to go...)
* Kepler-126
* Kepler-127
* Kepler-129
* Kepler-130
* Kepler-145
* Kepler-197

Photometric Kepler eccentricities part 3

---

systems/2MASS J0219-3925.xml

Added 2MASS J0219-3925

---

systems/VHS 1256-1257.xml

Added VHS 1256-1257 b.

---

systems/Kepler-278.xml
systems/Kepler-338.xml
systems/Kepler-444.xml
systems/Kepler-449.xml
systems/Kepler-450.xml

Closes #586 
Updated the following systems:
* Kepler-278
* Kepler-338
* Kepler-444
Added the following systems:
* Kepler-449
* Kepler-450

Photometric Kepler eccentricities part 4

---

systems/PTFO 8-8695.xml

Added PTFO 8-8695 b (candidate)

---

systems/EPIC 201208431.xml
systems/EPIC 201295312.xml
systems/EPIC 201338508.xml
systems/EPIC 201367065.xml
systems/EPIC 201384232.xml
systems/EPIC 201393098.xml
systems/EPIC 201403446.xml
systems/EPIC 201445392.xml
systems/EPIC 201465501.xml
systems/EPIC 201505350.xml
systems/EPIC 201546283.xml
systems/EPIC 201549860.xml
systems/EPIC 201565013.xml
systems/EPIC 201577035.xml
systems/EPIC 201596316.xml
systems/EPIC 201613023.xml
systems/EPIC 201617985.xml
systems/EPIC 201629650.xml
systems/EPIC 201635569.xml
systems/EPIC 201702477.xml
systems/EPIC 201736247.xml
systems/EPIC 201754305.xml
systems/EPIC 201828749.xml
systems/EPIC 201855371.xml
systems/EPIC 201912552.xml

Closes #639
Source http://arxiv.org/abs/1503.07866
EPIC 201208431: values updated, binary added
EPIC 201295312: values updated, binary added
EPIC 201338508: values updated, alt name added, binary added
EPIC 201367065: values updated, planet d is not mentioned in http://arxiv.org/abs/1503.07866
EPIC 201384232: values updated, alt name added, binary added
EPIC 201393098: values updated, alt name added
EPIC 201403446: values updated, binary added
EPIC 201445392: values updated, alt name added
EPIC 201465501: values updated, alt name added
EPIC 201505350: values updated, alt name added
EPIC 201546283: values updated, binary added
EPIC 201549860: values updated, binary added
EPIC 201565013: values updated
EPIC 201577035: values updated, alt name added, binary added
EPIC 201596316: values …

EPIC: values updated, alt names added, binaries added

---

systems/EPIC 201367065.xml

This reverts commit 7b3a22d906c15cb06886fccdc5ccaca82ec4345a.
Closes #650 (see that issue for reasoning)

Revert "Update EPIC 201367065.xml"

---

systems/EPIC 206011691.xml

Added EPIC 206011691

---

systems/HD 219134.xml

https://www.cfa.harvard.edu/pao/HD219134.pdf
four planets discovered by RV, two also with transittime
Closes #652

Create HD 219134.xml

---

systems/OGLE-05-169L.xml

Updated OGLE-2005-BLG-169L

---

systems/Gliese 849.xml
systems/HD 145934.xml
systems/HD 183263.xml
systems/HD 187123.xml
systems/HD 217107.xml
systems/HD 24040.xml
systems/HD 66428.xml
systems/HD 74156.xml

* HD 24040 (1 planet)
* HD 66428 (1 planet)
* HD 74156 (2 planets)
* HD 145934 (1 planet)
* HD 183263 (2 planets)
* HD 187123 (2 planets)
* HD 217107 (2 planets)
* Gliese 849 (2 planets)
Feng et al. (2015) http://adsabs.harvard.edu/abs/2015ApJ...800...22F
Additional identifiers and magnitudes from SIMBAD
Closes #442

Update parameters for 8 systems

---

systems/HIP 11915.xml

Planet data:
Bedell et al. (2015) http://fr.arxiv.org/abs/1507.03998
Additional stellar data:
Ramírez et al. (2014) http://cdsads.u-strasbg.fr/abs/2014A%26A...572A..48R
Coordinates, parallax and magnitudes from SIMBAD
Closes #636

Add HIP 11915 b.

---

systems/beta Pic.xml

Orbital parameters
Millar-Blanchaer et al. (2015) http://arxiv.org/abs/1508.04787
Stellar age
Mamajek & Bell (2014) http://adsabs.harvard.edu/abs/2014MNRAS.445.2169M
Radius/temperature
Currie et al. (2013) http://adsabs.harvard.edu/abs/2013ApJ...776...15C
Mass value
Snellen et al. (2014) http://adsabs.harvard.edu/abs/2014Natur.509...63S
Closes #668

Update Beta Pictoris

---

systems/tau Boo.xml

Planet/stellar parameters:
Borsa et al. (2015) http://adsabs.harvard.edu/abs/2015A%26A...578A..64B
Binary star orbit:
Drummond (2014) http://adsabs.harvard.edu/abs/2014AJ....147...65D
Closes #554

Update tau Boo

---

systems/KOI-55.xml

Krzesinski (2015) http://www.aanda.org/articles/aa/abs/2015/09/aa26346-15/aa26346-15.html
Closes #672

Move KOI-55 planets to "controversial" list.

---

systems/HD 18742.xml

Source: SIMBAD; discovered the mistake doing own observations

corrected declination sign

---

systems/51 Eri.xml

Montet et al. (2015) http://arxiv.org/abs/1508.05945
Closes #671

Update GJ 3305 AB (51 Eri system)

---

systems/WASP-120.xml
systems/WASP-122.xml
systems/WASP-123.xml

source http://arxiv.org/abs/1509.02210, additional alt names and magnitudes from SIMBAD
at two positions the paper mentions a HJD with 2 540000; i think this should be 245 0000, like all other occurrences of this number in the paper.
closes #682

added WASP-120, WASP-122, WASP-123

---

systems/KELT-10.xml
systems/KELT-8.xml

source
KELT-8 http://arxiv.org/abs/1505.06738
KELT-10 http://arxiv.org/abs/1509.02323, additional alt names and magnitudes from SIMBAD
closes #683

added KELT-8, KELT-10

---

systems/HD 82886.xml

corrected declination; discovered through own observations
Source SIMBAD
http://simbad.u-strasbg.fr/simbad/sim-id?Ident=hd82886&NbIdent=1&Radius=2&Radius.unit=arcmin&submit=submit+id

correction of DEC

---

systems/HD 96063.xml

corrected declination, error found by own observations
Source SIMBAD
http://simbad.u-strasbg.fr/simbad/sim-id?Ident=hd96063&NbIdent=1&Radius=2&Radius.unit=arcmin&submit=submit+id

corrected DEC

---

systems/1RXS1609.xml
systems/2M 044144.xml
systems/2MASS 0122-2439.xml
systems/CT Cha.xml
systems/EPIC 206011691.xml
systems/GSC 06214-00210.xml
systems/HIP 78530.xml
systems/VHS 1256-1257.xml

Not sure how you want to handle these but this seems the "OEC" way

changed unicode plus / minus in spectral type to error in xml tags

---

systems/OGLE-2015-BLG-0966L.xml

Street et al. (2015) http://arxiv.org/abs/1508.07027
Closes #677

Add OGLE-2015-BLG-0966

---

systems/WASP-36.xml

correction in RA (1 minute wrong); discovered by own observations
Source:
http://simbad.u-strasbg.fr/simbad/sim-id?Ident=wasp-36&NbIdent=1&Radius=2&Radius.unit=arcmin&submit=submit+id

correction in RA

---

systems/EPIC 206011691.xml

NASA Exoplanet Archive
http://exoplanetarchive.ipac.caltech.edu/cgi-bin/TblView/nph-tblView?app=ExoTbls&config=k2names

Add K2-21 designation to EPIC 206011691

---

systems/6 Lyn.xml
systems/HD 167042.xml
systems/HD 192699.xml
systems/HD 210702.xml
systems/kappa CrB.xml

Updates to 5 planetary systems around subgiant stars.
Minimum masses flagged with `type="msini"`

Updated orbits from Bowler et al. (2010)

---

systems/11 Com.xml
systems/11 UMi.xml
systems/14 And.xml
systems/7 CMa.xml
systems/81 Cet.xml
systems/HD 32518.xml

7 CMa, 11 Com, 11 UMi, HD 32518, 14 And, 81 Cet

Updates to 6 RV systems

---

cleanup.py
systems/HD 285507.xml
systems/Kepler-66.xml
systems/Kepler-67.xml
systems/NGC 2423 3.xml
systems/NGC 4349 No 127.xml
systems/PSR B1620-26.xml
systems/Pr0201.xml
systems/Pr0211.xml
systems/SAND364.xml
systems/YBP1194.xml
systems/YBP1514.xml
systems/eps Tau.xml

Added two new lists
* Planets in open clusters
* Planets in globular clusters
Added relevant planets to the lists.
Resolves #562

Lists for planets in open and globular clusters

---

oec.xsd

added
<xs:attribute name="msini" type="xs:string" use="optional"/>
<xs:enumeration value="Planets in open clusters"/>
<xs:enumeration value="Planets in globular clusters"/>

added new list entries

---

systems/KELT-2.xml

corrected typos

---

systems/Kepler-436.xml

corrected wrong transittime
http://arxiv.org/pdf/1402.6534.pdf

corrected wrong transittime

---

systems/14 Her.xml

Use dynamical two-planet solution
Goździewski et al. (2008) http://cdsads.u-strasbg.fr/abs/2008MNRAS.385..957G
Discovery reference for 14 Her c
Goździewski et al. (2006) http://cdsads.u-strasbg.fr/abs/2006ApJ...645..688G

Update 14 Her

---

systems/Gamma Leonis.xml

Additional orbital elements and error bars for planet
Han et al. (2010) http://adsabs.harvard.edu/abs/2010A%26A...509A..24H
Inclination and ascending node
Reffert & Quirrenbach (2011) http://adsabs.harvard.edu/abs/2011A%26A...527A.140R
Binary star separation and position angle from WDS
http://vizier.u-strasbg.fr/viz-bin/VizieR-S?WDS%20J10200%2b1950B

Update Gamma Leonis

---

systems/18 Del.xml
systems/HD 104985.xml
systems/HD 81688.xml
systems/xi Aql.xml

Sato et al. (2008) http://adsabs.harvard.edu/abs/2008PASJ...60..539S

Update 18 Del, xi Aql, HD 81688 and HD 104985

---

systems/24 Sex.xml
systems/30 Ari.xml
systems/42 Dra.xml
systems/HD 139357.xml
systems/HD 200964.xml

5 systems with updates for "new" orbital element tags and additional identifiers
* 24 Sextantis
* HD 200964
* 30 Arietis
* 42 Draconis
* HD 139357

Update 5 RV systems

---

systems/51 Eri.xml

Preliminary astrometric orbit
De Rosa et al. (2015) http://arxiv.org/abs/1509.07514

Update 51 Eri b

---

systems/V830 Tau.xml

Donati et al. (2015) http://adsabs.harvard.edu/abs/2015MNRAS.453.3706D
Coordinates, magnitudes and spectral type from SIMBAD
Closes #681

Add V830 Tau

---

systems/HD 12648.xml

corrected type for names PPM, 2MASS

Update HD 12648.xml

---

systems/2MASS J0219-3925.xml

added missing coords
source http://arxiv.org/abs/1505.01747

Update 2MASS J0219-3925.xml

---

systems/HD 87883.xml

Mass updated

---

systems/EPIC 206011691.xml

Fix incorrect units in EPIC 206011691

---

systems/HD 6434.xml

Planetary and stellar parameters:
Hinkel et al. (2015) http://arxiv.org/abs/1510.01746
Coordinates and additional identifiers from SIMBAD
Closes #735

Update HD 6434

---

systems/24 Sex.xml
systems/WASP-122.xml

corrections in descriptions

---

systems/EPIC 201637175.xml
systems/WASP-47.xml

Source: NASA Exoplanet Archive (K2 names table)

Add K2 names to EPIC 201637175 and WASP-47

---

systems/HD 219134.xml

Use parameters and designations from 6-planet APF solution
Vogt et al. (2015) http://arxiv.org/abs/1509.07912
Radius and inclination for inner planet from transit
Motalebi et al. (2015) http://arxiv.org/abs/1507.08532
Closes #719

Update HD 219134

---

systems/HATS-2.xml
systems/HATS-6.xml

improved coords, added fluxes

---

systems/7 CMa.xml
systems/HD 155233.xml

Add HD 155233, update 7 CMa

---

systems/KOI-89.xml

Ahlers, Barnes & Barnes (2015) http://arxiv.org/abs/1509.07930
Closes #752

Added KOI-89

---

systems/HAT-P-57.xml
systems/HATS-14.xml
systems/HATS-17.xml

HATS-17, HAT-P-57 (add); HATS-14 (update)

---

systems/61 Vir.xml
systems/75 Cet.xml
systems/HD 210702.xml
systems/HD 5608.xml
systems/kappa CrB.xml
systems/nu Oph.xml
systems/omi CrB.xml
systems/omi UMa.xml

61 Virginis + 7 systems from [Sato et al. (2012)](http://adsabs.harvard.edu/abs/2012PASJ...64..135S)
Relates to #722

Update 8 systems

---

systems/83 Leonis.xml
systems/91 Aquarii.xml
systems/HD 177830.xml
systems/HD 218566.xml
systems/HD 31253.xml
systems/tau Gem.xml

Relates to #722
From [Meschiari et al. (2011)](http://adsabs.harvard.edu/abs/2011ApJ...727..117M): 83 Leo, HD 177830, HD 31253, HD 218566
From [Mitchell et al. (2013)](http://adsabs.harvard.edu/abs/2013A%26A...555A..87M): 91 Aqr, Tau Gem (including binary star updates)

Update 6 systems

---

systems/GJ 1132.xml

added names, fluxes, spectraltype
improved coords
source SIMBAD

Update GJ 1132.xml

---

systems/EPIC 204129699.xml

Grziwa et al. (2015) http://arxiv.org/abs/1510.09149
Closes #760

Add EPIC 204129699

---

systems/HD 175607.xml

Mortier et al. (2015) http://arxiv.org/abs/1511.03941
Additional magnitudes and identifiers from SIMBAD

Add HD 175607

---

systems/FL Lyr.xml

Planetary parameters, stellar radii, orbital parameters:
Kozyreva et al. (2015) http://arxiv.org/abs/1510.02111
Binary period and epoch, stellar magnitudes, spectral types, masses, temperatures:
Popper et al. (1986) http://cdsads.u-strasbg.fr/abs/1986AJ.....91..383P
Closes #737

Add FL Lyr

---

systems/Alpha Centauri.xml

Error bars for orbital elements
Dumusque et al. (2012) http://cdsads.u-strasbg.fr/abs/2012Natur.491..207D
Binary star orbital elements
Pourbaix et al. (2002) http://adsabs.harvard.edu/abs/2002A%26A...386..280P
Stellar masses, temperatures, metallicities
Thévenin et al. (2002) http://adsabs.harvard.edu/abs/2002A%26A...392L...9T
Stellar radii, system parallax
Kervella et al. (2003) http://adsabs.harvard.edu/abs/2003A&A...404.1087K
Planet non-confirmed status
Hatzes (2013) http://cdsads.u-strasbg.fr/abs/2013ApJ...770..133H
Rajpaul et al. (2015) http://arxiv.org/abs/1510.05598
Possible transiting outer planet
Demory et al. (2015) http://adsabs.harvard.edu/abs/2015MNRAS.450.2043D
Coordinates and additional identifiers from SIMBAD
Closes #751

Update Alpha Centauri

---

systems/BD +48 738.xml
systems/BD-082823.xml
systems/BD-10 3166.xml
systems/BD-17 63.xml
systems/HD 145377.xml
systems/HD 153950.xml
systems/HD 20868.xml
systems/HD 240237.xml
systems/HD 73267.xml
systems/HD 96127.xml
systems/alf Ari.xml
systems/alf Tau.xml

Update 12 systems

---

systems/55 Cancri.xml

Interferometric radius and model-independent stellar mass
Ligi et al. (2015) http://arxiv.org/abs/1511.03197
Additional identifiers from SIMBAD

Update 55 Cancri

---

README.md
cleanup.py
oec.xsd

Added maximumrvtime element

---

systems/BD-114672.xml
systems/HD 103720.xml
systems/HD 108341.xml
systems/HD 113538.xml
systems/HD 30669.xml
systems/HD 564.xml

Moutou et al. (2015) http://adsabs.harvard.edu/abs/2015A%26A...576A..48M
Relates to #722

Update six systems

---

systems/WASP-135.xml

Spake et al. (2015) http://arxiv.org/abs/1511.05954
Closes #782

Add WASP-135

---

systems/HATS-15.xml
systems/HATS-16.xml

Ciceri et al. (2015) http://arxiv.org/abs/1511.06305
Closes #785

Add HATS-15 and HATS-16

---

systems/BD+15 2940.xml
systems/BD+20 1790.xml
systems/BD+20 274.xml
systems/BD+49 828.xml
systems/BD14 4559.xml
systems/BD20 2457.xml
systems/HD 216536.xml
systems/HD 219415.xml
systems/HD 233604.xml
systems/HD 240210.xml
systems/HD 95127.xml

Update 11 systems

---

systems/HR 8799.xml

Stellar properties
Baines et al. (2012) http://cdsads.u-strasbg.fr/abs/2012ApJ...761...57B
Orbital elements
Zurlo et al. (2015) http://arxiv.org/abs/1511.04083
Planetary radii, metallicities, temperatures and spectral types
Bonnefoy et al. (2015) http://arxiv.org/abs/1511.04082
Closes #772

Update HR 8799

---

systems/KOI-12.xml
systems/KOI-135.xml
systems/KOI-192.xml
systems/KOI-201.xml
systems/KOI-3680.xml
systems/KOI-3681.xml
systems/Kepler-117.xml
systems/Kepler-12.xml
systems/Kepler-13.xml
systems/Kepler-15.xml
systems/Kepler-17.xml
systems/Kepler-297.xml
systems/Kepler-41.xml
systems/Kepler-418.xml
systems/Kepler-422.xml
systems/Kepler-424.xml
systems/Kepler-44.xml
systems/Kepler-6.xml
systems/Kepler-7.xml
systems/Kepler-76.xml
systems/Kepler-77.xml
systems/Kepler-8.xml
systems/Kepler-87.xml
systems/Kepler-89.xml
systems/Kepler-9.xml
systems/Kepler-90.xml
systems/PH-2.xml

Updated 24 systems and added 3 new ones with "secure" status.
Closes #762

SOPHIE RVs for Kepler giant planets

---

systems/EPIC 201338508.xml
systems/EPIC 201367065.xml
systems/EPIC 201445392.xml
systems/EPIC 201505350.xml
systems/EPIC 201713348.xml
systems/EPIC 201754305.xml
systems/EPIC 203771098.xml
systems/EPIC 203826436.xml
systems/EPIC 204221263.xml
systems/EPIC 205071984.xml
systems/EPIC 206318379.xml
systems/EPIC 210490365.xml

Add EPIC 206318379 - closes #796 
Add EPIC 210490365 - closes #805 
Add/update 10 K2 multiplanet systems - closes #797

K2 new systems and updates

---

systems/MOA-2010-BLG-353L.xml
systems/MOA-2011-BLG-028L.xml
systems/MOA-2013-BLG-605L.xml

MOA-2010-BLG-353Lb - closes #734
MOA-2013-BLG-605Lb - closes #799
MOA-2011-BLG-028Lb - closes #814

Add three planets from microlensing

---

systems/Gliese 15.xml
systems/gamma Cephei.xml

Update gamma Cephei and Gliese 15

---

systems/Kepler-444.xml

Campante et al. (2015) http://cdsads.u-strasbg.fr/abs/2015ApJ...799..170C
Dupuy et al. (2015) http://arxiv.org/abs/1512.03428
Closes #819

Add multiple star information to Kepler-444

---

systems/HD 32963.xml

System parameters:
Rowan et al. (2015) http://arxiv.org/abs/1512.00417
Stellar spectral type:
XHIP catalog http://cdsarc.u-strasbg.fr/viz-bin/Cat?V/137D
Coordinates, parallax, magnitudes and additional identifers from SIMBAD
Closes #802

Add HD 32963

---

systems/Wolf 1061.xml

Planetary system properties
Wright et al. (2015) http://arxiv.org/abs/1512.05154
Stellar properties
Maldonado et al. (2015) http://cdsads.u-strasbg.fr/abs/2015A%26A...577A.132M
Coordinates, parallax, magnitudes and additional identifiers from SIMBAD
Closes #821

Add Wolf 1061

---

systems/HD 33844.xml
systems/HD 95872.xml
systems/Psi-1 Draconis.xml

HD 95872, Psi-1 Draconis - closes #813 
HD 33844 - closes #825

Four planets in three systems

---

systems/GJ 160.2.xml
systems/GJ 180.xml
systems/GJ 229.xml
systems/GJ 27.1.xml
systems/GJ 422.xml
systems/GJ 682.xml

Update the "GJ" systems. Relates to #722

Add msini flag to six RV systems

---

systems/EPIC 201208431.xml
systems/EPIC 201367065.xml
systems/EPIC 201384232.xml
systems/EPIC 201393098.xml
systems/EPIC 201465501.xml
systems/EPIC 201577035.xml
systems/EPIC 201596316.xml
systems/EPIC 201613023.xml
systems/EPIC 201629650.xml
systems/EPIC 201635569.xml
systems/EPIC 201736247.xml
systems/EPIC 201855371.xml
systems/EPIC 201912552.xml
systems/EPIC 206011691.xml
systems/EPIC 210490365.xml
systems/HAT-P-56.xml
systems/HIP 116454.xml
systems/WASP-28.xml
systems/WASP-47.xml

Source: NASA Exoplanet Archive

Update K2 identifiers and include 2MASS cross-index for K2 names

---

systems/KIC 10525077.xml
systems/KIC 3558849.xml
systems/KIC 5437945.xml
systems/KIC 5951458.xml
systems/KIC 8540376.xml
systems/KIC 9663113.xml

Wang et al. (2015) http://arxiv.org/abs/1512.02559
Additional data from NASA Exoplanet Archive
Closes #812

Add long-period planet candidates from Planet Hunters

---

systems/KOI-2939.xml
systems/Kepler-454.xml

Add Kepler-454 - closes #798 
Add KOI-2939 - closes #801

Add Kepler-454 and KOI-2939

---

systems/30 Ari.xml
systems/HD 20782.xml

Update 30 Ari - closes #765 
Update HD 20782 - closes #795

Update 30 Ari and HD 20782

---

systems/Kepler-105.xml
systems/Kepler-128.xml
systems/Kepler-26.xml
systems/Kepler-29.xml
systems/Kepler-307.xml
systems/Kepler-33.xml

Closes #740 
Closes #811 
(There's some overlap between the systems in the two papers, so the totals in the commits don't add up)

Update 6 systems with TTV-derived masses

---

systems/OGLE-2012-BLG-0026L.xml

Beaulieu et al. (2016) http://arxiv.org/abs/1601.01846
Coordinates and additional identifier from SIMBAD
Closes #836

Updated OGLE-2012-BLG-0026L

---

systems/EPIC 201465501.xml
systems/K2-26.xml

Schlieder et al. (2016) http://arxiv.org/abs/1601.02706
2MASS identifier for K2-26 from NASA Exoplanet Archive
Closes #841

Add K2-26, update K2-9

---

systems/HD 185269.xml
systems/HD 197037.xml
systems/HD 217786.xml
systems/Kepler-21.xml
systems/Kepler-68.xml

Add binary/multiple star information to 5 systems

---

systems/CoRoT-22.xml
systems/SAND364.xml
systems/YBP1194.xml
systems/YBP1514.xml

added fluxes, improved coords

---

systems/Gliese 163.xml
systems/Gliese 176.xml
systems/Gliese 86.xml

Updates for 3 RV systems

---

systems/HD 7449.xml

Binary star companion and revised orbital elements
Rodigas et al. (2015) http://arxiv.org/abs/1512.04540
Additional orbital elements for HD 7449 changes
Dumusque et al. (2011) http://adsabs.harvard.edu/abs/2011A%26A...535A..55D
Coordinates and additional identifiers from SIMBAD
Closes #822

Update HD 7449

---

systems/Gliese 176.xml
systems/WASP-119.xml
systems/WASP-124.xml
systems/WASP-126.xml
systems/WASP-129.xml
systems/WASP-133.xml

http://arxiv.org/abs/1602.01740
additionally data from SIMBAD
closes #862
and
XML correction for Gliese 176

Five new WASP planets

---

oec.xsd

Already used for the planets in HR 8799

Add metallicity to planet definition in schema file

---

systems/EPIC 201546283.xml
systems/EPIC 203771098.xml
systems/EPIC 206318379.xml

Source: NASA Exoplanet Archive

Add K2 names to 3 systems

---

README.md
cleanup.py
oec.xsd

Alternative to inclination.
Closes #880

Add impact parameter element

---

systems/EPIC 201295312.xml
systems/EPIC 201546283.xml
systems/EPIC 201577035.xml

K2-10, K2-27, EPIC 201295312
Closes #866

Update 3 K2 systems

---

systems/Gliese 179.xml
systems/HD 126614.xml
systems/HD 13931.xml
systems/HD 34445.xml

Data from [Howard et al. (2010)](http://adsabs.harvard.edu/abs/2010ApJ...721.1467H)
Relates to #722

Update 4 RV systems

---

systems/HD 39392.xml

I am not sure it qualifies as a planet in this database, but I have added it nonetheless. Cheers, Paul
Object is from my paper: http://arxiv.org/abs/1602.02749

Added HD 39392

---

systems/TRAPPIST-1.xml

Citation link:
http://www.nature.com/nature/journal/vaop/ncurrent/full/nature17448.html

Added IR magnitudes for TRAPPIST-1. 

---

systems/HD 131399.xml

Coordinates added

---

systems/TRAPPIST-1.xml

http://www.eso.org/public/archives/releases/sciencepapers/eso1615/eso1615a.pdf
line 114

another correction for declination

---

systems/TYC 3667-1280-1.xml

System parameters:
Niedzielski et al. (2016) http://arxiv.org/abs/1603.07581v1
Coordinates and magnitudes from SIMBAD
Closes #899

Add TYC 3667-1280-1 b

---

systems/Kepler-444.xml

Dupuy et al. (2016) http://adsabs.harvard.edu/abs/2016ApJ...817...80D

Correct orbital period of Kepler-444 outer binary

---

simbad_extractor.py

Fixed a missing closing bracket inside a string
Removing brackets in print statements to increase consistency
Change how to open file in non-main script to increase consistency

Minor changes (typo fixing, increase consistency)

---

systems/EPIC 211391664.xml
systems/HD 34445.xml

Vogt et al. (2017) "[A Six-planet System around the Star HD 34445](http://adsabs.harvard.edu/abs/2017AJ....154..181V)" + Gaia DR1 parallax/position from SIMBAD
Also fixed formatting in EPIC 211391664.xml

Update HD 34445

---

systems/HAT-P-54.xml
systems/HAT-P-66.xml
systems/HATS-12.xml
systems/HATS-18.xml
systems/HATS-22.xml
systems/HATS-26.xml
systems/HATS-3.xml
systems/WASP-127.xml
systems/WASP-131.xml
systems/WASP-140.xml
systems/WASP-141.xml
systems/WASP-142.xml

corrected DE
improved coords
added mags
reference: SIMBAD

WASP/HAT-P/HATS: corrected DE, added maps

---

systems/HD 40307.xml

Four-planet system from Diaz et al. (2016)
https://ui.adsabs.harvard.edu/?#abs/2016A%26A...585A.134D
Coordinates and distance and alternate identifiers from SIMBAD
Uncertainties for unconfirmed planets e and g from Tuomi et al. (2013)
http://adsabs.harvard.edu/abs/2013A%26A...549A..48T

Update HD 40307

---

systems/HD 16175.xml
systems/HD 164922.xml
systems/HD 191806.xml
systems/HD 214823.xml
systems/HD 219828.xml
systems/HD 221585.xml
systems/HD 42618.xml
systems/Rho Coronae Borealis.xml

Resolves 3 issues. See individual commit messages for details.

Additions and updates

---

systems/tau Ceti.xml

Add uncertainties from Tuomi et al. (2013)
https://www.aanda.org/articles/aa/abs/2013/03/aa20509-12/aa20509-12.html
Move b,c,d to retracted list, use four-planet system from Feng et al. (2017)
https://ui.adsabs.harvard.edu/?#abs/2017AJ....154..135F
Additional identifiers, coordinates and parallax from SIMBAD

Update Tau Ceti

---

systems/OGLE-2015-BLG-0051L.xml
systems/PTFO 8-8695.xml
systems/YBP401.xml

Update 3 systems, resolving 3 issues. Details in commit messages.

Update 3 systems

---

systems/83 Leonis.xml

Updated parameters for 83 Leo B, 83 Leo Bb, demoted 83 Leo Bc to the
"Controversial" list.
Kane et al. (2016) http://adsabs.harvard.edu/abs/2016ApJ...820L...5K
Resolves #877

Update 83 Leonis

---

systems/55 Cancri.xml
systems/CoRoT-29.xml
systems/Kepler-10.xml
systems/Kepler-91.xml

Resolves 4 issues. Details in commit messages.

Updates to four systems with transiting planets

---

systems/BD+20 594.xml

Stellar and planetary properties from Espinoza et al. (2016)
http://adsabs.harvard.edu/abs/2016ApJ...830...43E
Position, parallax and identifiers from SIMBAD
Resolves #854

Add BD+20 594 b

---

systems/VHS 1256-1257.xml

Primary is a binary, parameters from Stone et al. (2016)
http://adsabs.harvard.edu/abs/2016ApJ...818L..12S
Resolves #842

Update VHS 1256-1257

---

systems/CI Tau.xml
systems/FN Lyr.xml
systems/GJ 725.xml
systems/nu Oct.xml

Resolving four issues. Details in commit messages.

Add four systems

---

systems/EPIC 205071984.xml
systems/Gliese 504.xml
systems/HD 95086.xml
systems/Kappa Andromedae.xml
systems/OGLE-2013-BLG-0723L.xml
systems/WASP-103.xml
systems/WASP-66.xml
systems/WASP-87.xml

Addresses 6 issues, details in commit messages.

Updates to 8 systems

---

systems/TYC 9486-927-1.xml

Deacon, Schlieder & Murphy (2016)
http://adsabs.harvard.edu/abs/2016MNRAS.457.3191D
Resolves #849

Add TYC 9486-927-1/2MASS J2126-8140

---

systems/BD+26 1888.xml
systems/HD 122562.xml
systems/HD 12484.xml
systems/HD 143105.xml
systems/HD 220842.xml
systems/HD 35759.xml
systems/HD 39392.xml
systems/HIP 109384.xml
systems/HIP 109600.xml
systems/HIP 65407.xml

Adds/updates 10 systems. Resolves two issues. See commit messages for details.

Add/update planets from SOPHIE papers

---

systems/HD 141399.xml

Hébrard et al. (2016) http://adsabs.harvard.edu/abs/2016A%26A...588A.145H
Coordinates, magnitudes, parallax and additional identifiers from SIMBAD

Update HD 141399

---

systems/OGLE-2014-BLG-1760L.xml

Bhattacharya et al. (2016) http://adsabs.harvard.edu/abs/2016AJ....152..140B
MOA identifier from SIMBAD
Resolves #896

Add OGLE-2014-BLG-1760Lb

---

systems/BD+15 2375.xml
systems/HD 5583.xml

Niedzielski et al. (2016) http://adsabs.harvard.edu/abs/2016A%26A...588A..62N
Coordinates, magnitudes, parallaxes and additional identifiers from SIMBAD
Resolves #853

Update HD 5583, add BD+15 2375

---

systems/KIC 7177553.xml

Multiple star system properties from Lehmann et al. (2016)
http://adsabs.harvard.edu/abs/2016ApJ...819...33L
Planet candidate properties from Borkovits et al. (2016)
http://adsabs.harvard.edu/abs/2016MNRAS.455.4136B
System age from MacDonald & Mullan (2017)
https://ui.adsabs.harvard.edu/?#abs/2017ApJ...834...99M
KOI identifier from NASA Exoplanet Archive. Coordinates from SIMBAD.
Resolves #843

Add KIC 7177553

---

systems/EPIC 203311200.xml

System properties from Osborn et al. (2016)
http://adsabs.harvard.edu/abs/2016MNRAS.457.2273O
Parallax from TGAS
http://vizier.u-strasbg.fr/viz-bin/VizieR-5?-ref=VIZ5a2c3f1e4b46&-out.add=.&-source=I/337/tgas&recno=1835925&-out.orig=o
Resolves #820

Add EPIC 203311200

---

systems/Ross 128.xml

System properties from Bonfils et al. (2017)
https://www.eso.org/public/archives/releases/sciencepapers/eso1736/eso1736a.pdf
Coordinates, parallax, magnitudes and additional identifiers from SIMBAD

Add Ross 128

---

systems/Kapteyn.xml

Status of planet b from analysis in Anglada-Escudé et al. (2016)
http://adsabs.harvard.edu/abs/2016ApJ...830...74A
Parallax, magnitudes and additional identifiers from SIMBAD
Resolves #623

Update Kapteyn's star

---

systems/HD 47366.xml

System properties from Sato et al. (2016)
http://adsabs.harvard.edu/abs/2016ApJ...819...59S
Coordinates, parallax, magnitudes and additional identifiers from SIMBAD
Resolves #844

Add HD 47366

---

systems/HD 102329.xml
systems/HD 106270.xml
systems/HD 114783.xml
systems/HD 116029.xml
systems/HD 117207.xml
systems/HD 11964.xml
systems/HD 13931.xml
systems/HD 154345.xml
systems/HD 156279.xml
systems/HD 169830.xml
systems/HD 183263.xml
systems/HD 187123.xml
systems/HD 217107.xml
systems/HD 24040.xml
systems/HD 33142.xml
systems/HD 37605.xml
systems/HD 4203.xml
systems/HD 50499.xml
systems/HD 66428.xml
systems/HD 72659.xml
systems/HD 73534.xml
systems/HD 74156.xml
systems/HD 95089.xml
systems/HD 99706.xml

Update 24 systems. Details in commit messages.
Resolves #855

Update long period gas giants

---

systems/LHS 1140.xml

System parameters from Dittmann et al. (2017)
http://adsabs.harvard.edu/abs/2017Natur.544..333D

Add LHS 1140

---

systems/WASP-45.xml
systems/WASP-46.xml

Update WASP-45 and WASP-46

---

systems/HD 4113.xml

System properties from Cheetham et al. (arXiv 2017)
https://arxiv.org/abs/1712.05217v1
Separation and position angle of HD 4113 B from Mugrauer et al. (2014)
https://ui.adsabs.harvard.edu/?#abs/2014MNRAS.439.1063M

Update HD 4113

---

systems/LkCa 15.xml

Planetary properties from Sallum et al. (2015)
http://adsabs.harvard.edu/abs/2015Natur.527..342S
Distance from Kraus & Ireland (2012)
http://adsabs.harvard.edu/abs/2012ApJ...745....5K
Stellar mass and effective temperature from Simon et al. (2000)
https://ui.adsabs.harvard.edu/?#abs/2000ApJ...545.1034S
Coordinates, magnitudes, spectral type and additional identifiers from SIMBAD
Resolves #789

Update LkCa 15

---

systems/Kepler-80.xml
systems/Kepler-90.xml

Updates and additional planets, see commit messages for details

Update Kepler-80 and 90

---

systems/HD 10180.xml

Six-planet system, stellar parameters from Kane & Gelino (2014)
http://adsabs.harvard.edu/abs/2014ApJ...792..111K
Parameters for unconfirmed planets b,i,j from Tuomi (2012)
https://ui.adsabs.harvard.edu/?#abs/2012A%26A...543A..52T
Coordinates, magnitudes, parallax and additional identifiers from SIMBAD

Update HD 10180

---

systems/EPIC 201912552.xml

System parameters from Cloutier et al. (2017)
https://www.aanda.org/articles/aa/full_html/2017/12/aa31558-17/aa31558-17.html
Coordinates and magnitudes from SIMBAD

Update EPIC 201912552 (K2-18)

---

systems/V391 Peg.xml

Add uncertainties to orbit solution from Silvotti et al. (2007)
http://adsabs.harvard.edu/abs/2007Natur.449..189S
Moved planet to "Controversial" list: Silvotti et al. (arXiv 2017)
https://arxiv.org/abs/1711.10942v1
Coordinates and magnitudes from SIMBAD
Additional parameters from NASA Exoplanet Archive

Update V391 Peg

---

systems/WASP-34.xml
systems/WASP-8.xml

Additional planets WASP-8c and WASP-34c, plus update to existing properties (see commit messages for details)

Update WASP-8 and WASP-34

---

systems/KIC 12557548.xml
systems/KOI-2700.xml

Updates to KOI-2700 and KIC 12557548. See commit messages for details.

Update evaporating planets

---

systems/HD 147379.xml

System details from Reiners et al. (2017)
https://doi.org/10.1051/0004-6361/201732165
Physical parameters for EW Draconis from Gaidos & Mann (2014)
http://cdsarc.u-strasbg.fr/viz-bin/Cat?J/ApJ/791/54
Binary separation and position angle from WDS
http://cdsarc.u-strasbg.fr/viz-bin/Cat?B/wds
Coordinates, parallax, magnitudes and additional identifiers from SIMBAD

Add HD 147379

---

systems/HIP 65407.xml

DEC corrected; reference SIMBAD

DEC corrected

---

systems/HD 1461.xml
systems/HD 204313.xml

Details in commit messages.
Resolves #754

Update HD 1461 and HD 204313

---

systems/K2-138.xml

System parameters from Christiansen et al. (2018)
http://adsabs.harvard.edu/abs/2018AJ....155...57C
Coordinates and magnitudes from SIMBAD

Add five-planet system at K2-138

---

systems/WASP-144.xml
systems/WASP-145.xml
systems/WASP-158.xml
systems/WASP-159.xml
systems/WASP-162.xml
systems/WASP-168.xml
systems/WASP-172.xml
systems/WASP-173.xml

https://arxiv.org/pdf/1803.02224.pdf
New transiting hot Jupiters discovered by WASP-South, Euler/CORALIE and TRAPPIST-South
some fluxes added from SIMBAD
two of the host stars are binary systems

8 new transiting hot Jupiters discovered by WASP-South, Euler/CORALIE and TRAPPIST-South

---

systems/Epsilon Indi.xml

Planet properties from [Feng et al. (arXiv 2018)](https://arxiv.org/abs/1803.08163v1)
Stellar properties for Epsilon Indi A from [Demory et al. (2009)](https://ui.adsabs.harvard.edu/?#abs/2009A%26A...505..205D)
Magnitudes for Epsilon Indi A from SIMBAD
Epsilon Indi AB separation and position angle from WDS
Orbital parameters for Epsilon Indi Ba,Bb from [Cardoso et al. (2009)](http://adsabs.harvard.edu/abs/2009AIPC.1094..509C)
Stellar properties for Epsilon Indi Ba,Bb from [King et al. (2010)](http://adsabs.harvard.edu/abs/2010A%26A...510A..99K)

Add Epsilon Indi

---

systems/HD 26965.xml

Confirmation of planetary nature, updated parameters
Ma et al. (arXiv 2018) https://arxiv.org/abs/1807.07098v1

Update HD 26965 (40 Eridani)

---

systems/TRAPPIST-1.xml

A couple more identifiers for this system

Add K2 and EPIC IDs to TRAPPIST-1

---

systems/FN Lyr.xml
systems/Kepler-450.xml

added missing lastupdate
reference: SIMBAD

added missing lastupdate

---

systems/HD 59686.xml

Add stellar binary information and update orbital parameters from [Ortiz et al. (2016)](https://ui.adsabs.harvard.edu/?#abs/2016A%26A...595A..55O)

Update HD 59686

---

systems/2MASS J02495639-0557352.xml

Planet and binary system properties from Dupuy et al. (arXiv 2018)
https://arxiv.org/abs/1807.05235v2
Coordinates and Gaia DR2 identifier from SIMBAD

Add 2MASS J02495639-0557352 c

---

systems/CoRoT-20.xml

System parameters from [Rey et al. (2018)](https://arxiv.org/abs/1807.01229v1)
Coordinates, parallax and Gaia identifier from SIMBAD

Add CoRoT-20 c and update system parameters

---

systems/HAT-P-11.xml

Planet and stellar parameters from [Yee et al. (2018)](http://adsabs.harvard.edu/abs/2018AJ....155..255Y)
HAT-P-11b inclination, errors on period, transit time from [Huber et al. (2017)](http://adsabs.harvard.edu/abs/2017A%26A...597A.113H)
HAT-P-11b spin orbit misalignment from [Hirano et al. (2011)](http://adsabs.harvard.edu/abs/2011PASJ...63S.531H)
Coordinates and additional identifiers from SIMBAD

Add HAT-P-11 c and update system parameters

---

systems/WASP-189.xml

https://arxiv.org/pdf/1809.04897.pdf
WASP-189b: an ultra-hot Jupiter transiting the bright A star HR 5599 in a polar orbit
additional data from SIMBAD

WASP-189b an ultra-hot Jupiter

---

systems/HD 39091.xml
systems/WASP-189.xml

New planet from TESS in the Pi Mensae system, plus a fix to the formatting in WASP-189 that the cleanup script caught.

Update the Pi Mensae system

---

.gitignore
systems/55 Cancri.xml
systems/HD 39091.xml
systems/TRAPPIST-1.xml

Updates to 55 Cancri and TRAPPIST-1 and a missing orbital inclination for Pi Mensae c. Also adds VS Code working directory to the ignored files list.

Update multiplanet systems

---

systems/Epsilon Indi.xml

Dynamical masses and orbital elements for Epsilon Indi Ba/Bb: [Dieterich et al. (2018)](https://arxiv.org/abs/1807.09880v1)
Gaia DR2 identifier, coordinates and parallax from SIMBAD

Update Epsilon Indi

---

systems/NGTS-10.xml
systems/NGTS-2.xml
systems/NGTS-3.xml
systems/NGTS-4.xml
systems/NGTS-5.xml
systems/NGTS-6.xml

ngts-2 https://arxiv.org/abs/1805.10449
ngts-3 https://arxiv.org/abs/1805.01378
ngts-4 https://arxiv.org/abs/1809.00678
ngts-5 https://arxiv.org/abs/1905.02593
ngts-6 https://arxiv.org/abs/1904.07997
ngts-10 https://arxiv.org/abs/1909.12424
and SIMBAD data

added missing NGTS exoplanets

---

KELT-19.xml
systems/KELT-21.xml
systems/KELT-23.xml

kelt-19	https://arxiv.org/abs/1709.07010
kelt-21	https://arxiv.org/abs/1712.03241
kelt-23	https://arxiv.org/abs/1903.00031
and data from SIMBAD

added missing KELT exoplanets

---

systems/WASP-174.xml
systems/WASP-175.xml
systems/WASP-177.xml
systems/WASP-180.xml
systems/WASP-181.xml
systems/WASP-182.xml
systems/WASP-183.xml

wasp-174	https://arxiv.org/abs/1802.00766
wasp-175	https://arxiv.org/abs/1904.10388
wasp-177	https://arxiv.org/abs/1903.06622
wasp-180	https://arxiv.org/abs/1903.08002
wasp-181	https://arxiv.org/abs/1903.06622
wasp-182	https://arxiv.org/abs/1904.10388
wasp-183	https://arxiv.org/abs/1903.06622
and data from SIMBAD

added missing WASP exoplanets

---

systems/HATS-50.xml
systems/KELT-19.xml

KELT-19	https://arxiv.org/abs/1709.07010
HATS-50	https://arxiv.org/abs/1712.04324
yesterday, KELT-19 was added to the wrong directory. please remove the yesterday added KELT-19

added KELT-19 and HATS-50

---

systems/HATS-51.xml
systems/HATS-52.xml
systems/HATS-53.xml
systems/HATS-54.xml
systems/HATS-55.xml
systems/HATS-56.xml
systems/HATS-57.xml
systems/HATS-58.xml
systems/HATS-59.xml
systems/HATS-60.xml
systems/HATS-61.xml
systems/HATS-62.xml
systems/HATS-63.xml
systems/HATS-64.xml
systems/HATS-65.xml
systems/HATS-66.xml
systems/HATS-67.xml
systems/HATS-68.xml
systems/HATS-69.xml
systems/HATS-71.xml

HATS-51	https://arxiv.org/abs/1712.04324
HATS-52	https://arxiv.org/abs/1712.04324
HATS-53	https://arxiv.org/abs/1712.04324
HATS-54	https://arxiv.org/abs/1812.07668
HATS-55	https://arxiv.org/abs/1812.07668
HATS-56	https://arxiv.org/abs/1812.07668
HATS-57	https://arxiv.org/abs/1812.07668
HATS-58	https://arxiv.org/abs/1812.07668
HATS-59	https://arxiv.org/abs/1805.05925
HATS-60	https://arxiv.org/abs/1809.01048
HATS-61	https://arxiv.org/abs/1809.01048
HATS-62	https://arxiv.org/abs/1809.01048
HATS-63	https://arxiv.org/abs/1809.01048
HATS-64	https://arxiv.org/abs/1809.01048
HATS-65	https://arxiv.org/abs/1809.01048
HATS-66	https://arxiv.org/abs/1809.01048
HATS-67	https://arxiv.org/abs/1809.01048
HATS-68	https://arxiv.org/abs/1809.01048
HATS-69	https://arxiv.org/abs/1809.01048
HATS-71 …

added missing HATS exoplanets

---

systems/EPIC 228754001.xml
systems/K2-109.xml
systems/K2-163.xml
systems/WASP-180.xml

coordinate corrections in DE for
K2-109, K2-163, EPIC 228754001, WASP-180
after own observations, checked with/get from SIMBAD

Corrections in DE for four systems

---

systems/EPIC 228813918.xml

Correction in DE
Own Observation
Source: SIMBAD

Update EPIC 228813918.xml

---

systems/EPIC 228735255.xml

Correction in DE
Own Observation
Source: SIMBAD

Update EPIC 228735255.xml

---

systems/BD+03 2562.xml
systems/EPIC 201546283.xml
systems/EPIC 201635569.xml
systems/EPIC 201736247.xml
systems/EPIC 228735255.xml
systems/EPIC 228754001.xml
systems/EPIC 228813918.xml
systems/K2-108.xml

changes in Vmag and distances (additions, updates)

---

systems/HIP 68468.xml

corrected DE, updated distance, coordinate

Update HIP 68468.xml

---

oec.xsd

Forgot to do this when I added it to the cleanup script

Add astrometry to discovery methods in oec.xsd

---

systems/Alpha Centauri.xml

Please review the commit, I know that there is a newly discovered planet in Proxima Centauri So I wanted to add it to the catalogue. 
Sorry I did not realize that I was naming the commit what it says so please edited to something like "Added Proxima Centauri c" since it does not allow me to edit the name.

Proxima Centauri c

---

systems/HD 75898.xml

https://www.iau.org/public/themes/naming_stars/
https://www.iau.org/public/themes/naming_exoplanets/

Update HD 75898.xml
