- systems/55 Cancri.xml
Updated the parameters of 55 Cancri from Baluev (2015). I think this could perhaps be relevant for closing #282 but since that was about an unconfirmed obliquity measurement I leave that to your judgement.
> Updated 55 Cancri.

- systems/Fomalhaut.xml
As this object may be a [dust cloud not associated with a planet](http://arxiv.org/abs/1412.1129) or even possibly a [background neutron star](http://arxiv.org/abs/1501.07083), I think this one should be moved to the "Controversial" list. I've also removed the mass estimate that was based on the assumption that the optical emission was coming from the surface of a gas giant planet, which is inconsistent with the ring-crossing orbit (if it is part of the system).
> Moved Fomalhaut b to "Controversial" list.

- systems/HIP 116454.xml
- systems/WASP-28.xml
[WASP-28](http://exoplanetarchive.ipac.caltech.edu/cgi-bin/DisplayOverview/nph-DisplayOverview?objname=WASP+28+b&type=CONFIRMED_PLANET) and [HIP 116454](http://exoplanetarchive.ipac.caltech.edu/cgi-bin/DisplayOverview/nph-DisplayOverview?objname=HIP+116454+b&type=CONFIRMED_PLANET) have received IDs from the K2 mission. See also http://exoplanetarchive.ipac.caltech.edu/docs/K2Numbers.html
> Added K2 IDs to WASP-28 (K2-1) and HIP 116454 (K2-2)

- README.md
- cleanup.py
- oec.xsd
- systems/Upsilon Andromedae.xml
Added the meananomaly tag to the cleanup script, schema and README
Updated the Upsilon Andromedae system to the orbital solution PRO2 from [Deitrick et al. (2015)](http://adsabs.harvard.edu/abs/2015ApJ...798...46D)
The solution PRO1 was not used due to the difficulty of reconciling this solution with the phase curve data for planet b.
Closes #406
> Update Upsilon Andromedae

- systems/KOI-680.xml
- systems/KOI-806.xml
- systems/Kepler-25.xml
- systems/Kepler-33.xml
- systems/Kepler-36.xml
Culled from the Kepler bulk update.
Cases where KIC numbers were incorrect or KOI nnn.nn designations were assigned to incorrect planets.
> Fix mismatched KOI/KIC designations

- systems/Kepler-445.xml
NASA KOI Catalog lists only two KOIs for this system, corresponding to planets b and c. There is no KOI-2704.03, and the Kepler names table lists Kepler-445 d as not being in the KOI list. The discovery paper [Muirhead et al. (2013)](http://adsabs.harvard.edu/abs/2015ApJ...801...18M) also notes that the third object in this system was missed by the Kepler pipeline.
> Kepler-445 d has no corresponding KOI identifer.

- systems/Kepler-20.xml
- systems/Kepler-22.xml
- systems/Kepler-410.xml
- systems/Kepler-412.xml
- systems/Kepler-418.xml
- systems/Kepler-421.xml
- systems/Kepler-447.xml
- systems/Kepler-45.xml
- systems/Kepler-48.xml
- systems/Kepler-50.xml
- systems/Kepler-51.xml
- systems/Kepler-57.xml
- systems/Kepler-59.xml
- systems/Kepler-60.xml
- systems/Kepler-62.xml
- systems/Kepler-74.xml
- systems/Kepler-87.xml
Further updates culled from the bulk Kepler update - mainly addition of missing designation forms and some corrections to forms. See individual commit messages for details
> KOI and KIC identifiers

- systems/WASP-90.xml
Closest 2MASS source to the coordinates is [2MASS 21020767+0703224](http://vizier.u-strasbg.fr/viz-bin/VizieR-5?-ref=VIZ5525a5cc7e0a&-out.add=.&-source=II/246/out&2MASS===21020767%2b0703224) but I have no way of confirming this is the correct identifier. For now I remove the incorrect 2MASS identifier which belongs to WASP-76.
Closes #529
> Remove incorrect 2MASS identifier from WASP-90

- systems/KOI-1873.xml
- systems/KOI-2672.xml
- systems/KOI-370.xml
- systems/KOI-523.xml
The 4 systems below appear to have their KOI letter designations set based on the KOI numbering, with .01=b, .02=c, despite the Kepler designations being reversed with respect to this. As far as I can tell, the reversed letters from the "KOI convention" have not actually been used, so there is no reason to preserve this inverted convention.
Discovery paper for all systems is [Xie (2014)](http://adsabs.harvard.edu/abs/2014ApJS..210...25X)
> Mismatched letter designations (Xie 2014 planets)

- systems/Kepler-296.xml
Matches format used in discovery paper (Rowe et al. 2014)
Reflects uncertainty about which star in the binary is the host star (Lissauer et al. 2014)
Rowe et al. (2014) http://cdsads.u-strasbg.fr/abs/2014ApJ...784...45R
Lissauer et al. (2014) http://cdsads.u-strasbg.fr/abs/2014ApJ...784...44L
> Kepler-296: removed binary star designation from planets

- systems/Gliese 3470.xml
(Probably better to do Gliese name cleanup under a separate ticket, so leaving that out of this version)
Data update from 2014 revision to parameters.
Biddle et al. (2014) http://adsabs.harvard.edu/abs/2014MNRAS.443.1810B
Closes #280
> Update Gliese 3470 b.

- systems/HD 110014.xml
- systems/HD 11977.xml
- systems/HD 122430.xml
- systems/HD 47536.xml
- systems/HD 70573.xml
* New planet HD 110014 c
* Non-confirmations of HD 47536 c, HD 70573 b, HD 122430 b
* Orbital elements updates for confirmed planets
Soto et al. (2015) http://arxiv.org/abs/1505.04796
Closes #588
> Update RAFT planets

- systems/HAT-P-7.xml
- systems/Kepler-25.xml
* Spin-orbit alignment (lambda) information for Kepler-25c and HAT-P-7b
* Updated stellar parameters
Benomar et al. (2014) http://adsabs.harvard.edu/abs/2014PASJ...66...94B
For this change I used the sky-projected misalignment (λ) rather than the three-dimensional misalignment (ψ) as this seems to be what is implied by the definition of the `<spinorbitalignment>` element in the README file.
Closes #293
> Updated Kepler-25 and HAT-P-7

- oec.xsd
added "W" to allow the spectraltype white dwarf (WD)
HU Aqr has such a spectraltype definition
> allow spectraltype white dwarf

- systems/KOI-285.xml
- systems/Kepler-23.xml
- systems/Kepler-25.xml
- systems/Kepler-37.xml
- systems/Kepler-65.xml
- systems/Kepler-68.xml
Updates for #586 
* Kepler-10: leaving with RV orbits, no change
* Kepler-23: updated b,c,d
* Kepler-25: updated b,c
* Kepler-37: updated b,c,d + fixed missing error bars
* Kepler-65: updated b,c
* Kepler-68: updated b + fixed missing error bars. Eccentricity determination for c unreliable so omitted
* Kepler-92: planet d confirmed, updated b,c. Fixed missing transit times
> Photometric Kepler eccentricities part 1

- systems/KIC 9632895.xml
Per [NASA Exoplanet Archive](http://exoplanetarchive.ipac.caltech.edu/cgi-bin/DisplayOverview/nph-DisplayOverview?objname=Kepler+453+b&type=CONFIRMED_PLANET).
While that page also gives KOI-1451.01 as an alternate designation for the planet, the [KOI Overview](http://exoplanetarchive.ipac.caltech.edu/cgi-bin/DisplayOverview/nph-DisplayOverview?objname=K01451.01&type=KEPLER_CANDIDATE) indicates that this designation is for the 27-day orbit, i.e. it represents the secondary star. I'm therefore leaving KOI-1451.01 on the star KIC 9632895 B.
> Added Kepler-453 designation to KIC 9632895

- systems/HAT-P-56.xml
Source: NASA Exoplanet Archive (K2 names table)
http://exoplanetarchive.ipac.caltech.edu./cgi-bin/TblView/nph-tblView?app=ExoTbls&config=k2names
> Add K2 designation to HAT-P-56

- systems/51 Eri.xml
51 Eri A,b properties:
Macintosh et al. (2015) http://arxiv.org/abs/1508.03084
Sky coordinates, B and V magnitudes and additional names from SIMBAD
Multiple star data, including magnitudes for GJ 3305:
WDS data http://vizier.u-strasbg.fr/viz-bin/VizieR-S?WDS%20J04376-0228Ca%2cCb
Orbital information for GJ 3305:
Delorme et al. (2012) http://cdsads.u-strasbg.fr/abs/2012A%26A...539A..72D
Spectral types and masses for GJ 3305:
Janson et al. (2012) http://cdsads.u-strasbg.fr/abs/2012ApJ...754...44J
Closes #662
> Add 51 Eridani

- systems/2M 044144.xml
Include outer binary system 2M0441+2301
Bowler & Hillenbrand (2015) http://arxiv.org/abs/1509.01658
I've left the file/system name as-is, though the combined system uses 2M0441+2301 rather than 2M 044144 which refers to the Bab subsystem.
Closes #680
> Update 2M 044144

- systems/WASP-47.xml
Spin-orbit alignment for WASP-47b
Sanchis-Ojeda et al. (2015) http://arxiv.org/abs/1509.05337
Closes #696
> Updated WASP-47

- oec.xsd
1 - "type" in tag "name" is now accepted (since KIC 8435766.xml uses type="pri")
2 - optimizations in regex syntax
> allow "type" in tag "name"

- systems/16 Cygni.xml
Use 16 Cyg A as system primary and for sky coordinates (SIMBAD)
Recalculate separation and position angle for AB from ICRS
coordinates (SIMBAD)
Added magnitudes and alternate identifiers from SIMBAD
Magnitude for 16 Cygni C from WDS
http://vizier.u-strasbg.fr/viz-bin/VizieR-S?WDS%20J19418%2b5032A
Recalculate distance and physical separation from weighted average of
parallaxes for 16 Cyg A and 16 Cyg B.
van Leeuwen (2007) http://cdsarc.u-strasbg.fr/viz-bin/Cat?I/311
Added periastron/periastrontime for 16 Cyg Bb and error bars
Wittenmyer et al. (2007) http://adsabs.harvard.edu/abs/2007ApJ...654..625W
Astrometric stellar properties for 16 Cyg A and B
Davies et al. (2015) http://cdsads.u-strasbg.fr/abs/2015MNRAS.446.2959D
Recalculated planet mass and semimajor axis with astrometric stellar …
> Updated 16 Cygni

- systems/8 Ursae Minoris.xml
- systems/HD 11755.xml
- systems/HD 12648.xml
- systems/HD 132406.xml
- systems/HD 24064.xml
Four radial velocity planets (BOAO)
HD 11755,HD 12648,HD 24064,8 Ursae Minoris
source
http://arxiv.org/abs/1509.09012, additional alt names and magnitudes from SIMBAD
closes #721
> Four radial velocity planets (BOAO)

- systems/EPIC 203771098.xml
[Petigura et al. (2015)](http://arxiv.org/abs/1511.04497)
Closes #779
> Add EPIC 203771098

- cleanup.py
Uses system-specific line-endings in the XML files, making it easier to work with Git's default line-ending conversion rules on Windows.
> Update cleanup script to output files in text mode

- cleanup.py
- systems/51 Eri.xml
- systems/Alpha Centauri.xml
- systems/EPIC 201367065.xml
- systems/Gliese 15.xml
- systems/HR 8799.xml
- systems/KOI-1474.xml
- systems/Kepler-444.xml
- systems/gamma Cephei.xml
- systems/tau Boo.xml
The "ascendingnode" tag was not in the list of numeric tags, so the corresponding error tag was not filled in if only one was provided.
This pull request fixes this omission and updates the relevant data files.
> Fix for ascendingnode element

- systems/Kepler-1013.xml
According to the NASA Exoplanet Archive, right ascension for Kepler-1013 b is 19 20 59.54
Ref: http://exoplanetarchive.ipac.caltech.edu/cgi-bin/DisplayOverview/nph-DisplayOverview?objname=Kepler-1013+b&type=CONFIRMED_PLANET
> Fix Kepler-1013 b right ascension

- oec.xsd
Related to `/systems/Kepler-1000.xml`  where "new" is used, it must be defined for XSD validation.
https://github.com/OpenExoplanetCatalogue/open_exoplanet_catalogue/blob/master/systems/Kepler-1000.xml#L18
> Add the "new" subelement for the planet element

- systems/KELT-17.xml
The value '13 44 07.2' is not accepted by the pattern `(\+|\-)(\d{2} [0-5]\d [0-5]\d)(\.\d+)?`
> Fix system declination

- oec.xsd
Related to `/systems/Kepler-1172.xml`
The value '+37 45 60' is not accepted by the pattern '(\+|\-)(\d{2} [0-5]\d [0-5]\d)(\.\d+)?'.
https://github.com/OpenExoplanetCatalogue/open_exoplanet_catalogue/blob/master/systems/Kepler-1172.xml#L4
> Fix declinationdef validation pattern

- systems/Kepler-1099.xml
The value '19 14 60' is not accepted by the pattern '[0-2]\d [0-5]\d [0-5]\d(.\d+)?'.
https://github.com/OpenExoplanetCatalogue/open_exoplanet_catalogue/blob/master/systems/Kepler-1099.xml#L3
ref. http://exoplanetarchive.ipac.caltech.edu/cgi-bin/DisplayOverview/nph-DisplayOverview?objname=Kepler-1099+b&type=CONFIRMED_PLANET
Do you think we could make pattern more precise, with 2 digits ? Current one does not accept 59.99 which seems to be a great precision.
> Fix right ascension

- systems/Kepler-1172.xml
The value '+37 45 60' is not accepted by the pattern '(+|-)(\d{2} [0-5]\d [0-5]\d)(.\d+)?'.
https://github.com/OpenExoplanetCatalogue/open_exoplanet_catalogue/blob/master/systems/Kepler-1172.xml#L4
ref. http://exoplanetarchive.ipac.caltech.edu/cgi-bin/DisplayOverview/nph-DisplayOverview?objname=Kepler-1172+b&type=CONFIRMED_PLANET
> Fix declination

- oec.xsd
Ref. to #958, seconds can not be 60
> Fix declinationdef pattern

- systems/HD 131399.xml
Planet is likely a background star. Nielsen et al. (2017)
http://adsabs.harvard.edu/abs/2017AJ....154..218N
Primary star HD 131399 A is a spectroscopic binary, using Aa1 and Aa2 as the
component designations as these are not yet assigned, and Ab is already used
for the planet candidate. Lagrange et al. (2017)
https://www.aanda.org/articles/aa/pdf/forth/aa30978-17.pdf
Position angle and separation for the HD 131399 BC binary from WDS
http://vizier.u-strasbg.fr/viz-bin/VizieR-5?-ref=VIZ5a2be9538522&-out.add=.&-source=B/wds/wds&recno=80499
K-magnitudes for BC, missing orbital elements for A-BC and BC from
Wagner et al. (2016) http://adsabs.harvard.edu/abs/2016Sci...353..673W
Parallax and additional identifiers from SIMBAD
> Update HD 131399

- systems/HD 219134.xml
Update planet designations to use current nomenclature.
Updated details for planets b, c, f and d from Gillon et al. (2017)
http://adsabs.harvard.edu/abs/2017NatAs...1E..56G
Updated details for planet h from Johnson et al. (2016)
http://adsabs.harvard.edu/abs/2016ApJ...821...74J
Use periastron time instead of mean anomaly for planet g from Vogt et al. (2015)
http://adsabs.harvard.edu/abs/2015ApJ...814...12V
Added details of retracted candidate e from Motalebi et al. (2015)
http://adsabs.harvard.edu/abs/2015A%26A...584A..72M
Resolves #869
> Update HD 219134

- systems/Gliese 436.xml
Parameters including spin-orbit alignment from Bourrier et al. (arXiv 2017) https://arxiv.org/abs/1712.06638v1
Update parameters for UCF-1.01 and add UCF-1.02 from Stevenson et al. (2012) https://ui.adsabs.harvard.edu/?#abs/2012ApJ...755....9S
Note non-confirmation of UCF-1.01 from Stevenson et al. (2014) https://ui.adsabs.harvard.edu/?#abs/2014ApJ...796...32S
Remove the name Gliese 436 c from UCF-1.01 as this designation appears to be used for the hypothetical perturbing planet that is inducing the eccentricity of Gliese 436 b, which is not the case for UCF-1.01.
> Update Gliese 436

- systems/HD 26965.xml
* Parameters for HD 26965 from [Díaz et al. (2018)](https://arxiv.org/abs/1801.03970)
* 40 Eri BC orbit and masses from [Mason et al. (2017)](http://adsabs.harvard.edu/abs/2017AJ....154..200M)
* 40 Eri B temperature, radius and age from [Bond et al. (2017)](https://ui.adsabs.harvard.edu/?#abs/2017ApJ...848...16B)
* 40 Eri C metallicity from [Newton et al. (2014)](http://cdsarc.u-strasbg.fr/viz-bin/Cat?J/AJ/147/20)
* 40 Eri AB separation and position angle from [WDS](http://cdsarc.u-strasbg.fr/viz-bin/Cat?B/wds)
* Coordinates, magnitudes, parallax and additional identifiers from SIMBAD
> Add unconfirmed planet around HD 26965 (40 Eri A)

- systems/HD 233604.xml
- systems/WASP-80.xml
Check for duplicate names indicated possible duplicates for two pairs of systems
* HD 233604 = BD+15 2940
* WASP-79 = WASP-80
These turned out to be due to incorrect designations in the files for HD 233604 and WASP-80, rather than being genuine duplicates.
> Fix incorrect designations leading to false-positive duplicates

- systems/WASP-173.xml
Independently discovered as KELT-22Ab. Added binary separation, position
angle, primary infrared magnitudes and secondary spectral type from
Labadie-Bartz et al. (arXiv 2018) https://arxiv.org/abs/1803.07559v1
Secondary magnitude from Hellier et al. (arXiv 2018)
https://arxiv.org/abs/1803.02224v1
Additional identifiers from SIMBAD
> Update WASP-173 (KELT-22)

- systems/Epsilon Indi.xml
- systems/omi CrB.xml
Duplicate names GJ 845 Bb (accidentally also applied to the Ba component) and omi CrB.
> Fix duplicate names

- systems/Kepler-503.xml
Updated system data from [Cañas et al. (2018)](http://adsabs.harvard.edu/abs/2018ApJ...861L...4C)
Coordinates, magnitudes and Gaia identifier from SIMBAD
> Update Kepler-503: companion is non-planetary

- cleanup.py
- systems/HD 176051.xml
This one is currently listed incorrectly as an RV planet, but should be astrometry (which needs to be added to cleanup.py... also as advance preparation for Gaia)
Fix discovery method, add binary system details, uncertainties on planet properties and name "Inrakluk" from [Muterspaugh et al. (2010)](https://ui.adsabs.harvard.edu/?#abs/2010AJ....140.1657M)
Coordinates, parallax and additional identifiers from SIMBAD.
> Update HD 176051

- systems/HD 180617.xml
Planet parameters for HD 180617 b from [Kaminski et al. (arXiv 2018)](https://arxiv.org/abs/1808.01183v1)
Planet parameters for VB 10 b and stellar mass of VB 10 from [Pravdo & Shaklan (2009)](https://ui.adsabs.harvard.edu/?#abs/2009ApJ...700..623P)
Radial velocity non-confirmation of VB 10 b:
- [Bean et al. (arXiv 2009)](https://arxiv.org/abs/0912.0003v2)
- [Anglada-Escudé et al. (2010)](https://ui.adsabs.harvard.edu/?#abs/2010ApJ...711L..24A/abstract)
Astrometric non-confirmation of VB 10 b from [Lazorenko et al. (2011)](https://ui.adsabs.harvard.edu/?#abs/2011A&A...527A..25L/abstract)
Binary parameters from [WDS](http://vizier.u-strasbg.fr/viz-bin/VizieR-5?-ref=VIZ5b7334319f78&-out.add=.&-source=B/wds/wds&recno=106640)
Coordinates, magnitudes and additional designations from SIMBAD
> Add HD 180617

- README.md
Python 2.x is deprecated and should be the exception. So I swapped the two examples, making Python 3 the default.
> Make Python 3 default in README example

- README.md
> Add distinct examples for Python 2 and 3 in the readme
